server:
  port: 8080

spring:
  data:
    redis:
      host: localhost
      port: 6379

  mongodb:
    uri: ${MONGO_URI}
    username: ${MONGO_USER}
    password: ${MONGO_PASS}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USER}
    password: ${SMTP_PASS}
    properties:
      mail:
        SMTP:
          enable: true
          STARTTLS:
            auth: true

jwt:
  secret: ${JWT_SECRET}
  access_time: ${JWT_ACCESS_TIME}
  refresh_time: ${JWT_REFRESH_TIME}